# Generated by Django 3.1.5 on 2021-01-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
