# Generated by Django 3.1.5 on 2021-02-05 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210131_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='NameInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nameinfo'),
        ),
    ]
